---
- name: Check Installed Packages
  hosts: test_hosts
  gather_facts: true
      become: yes
      become_method: sudo

  tasks:
    - name: List Installed Packages
      shell: dpkg -l
      register: dpkg_output
      ignore_errors: yes

    - name: Display Installed Packages
      debug:
        var: dpkg_output.stdout_lines
