---
- name: Check Installed Packages
  hosts: test_hosts
  gather_facts: true
  become: yes
  become_method: sudo
  
 tasks:
    - name: Vérifier si Tomcat est installé
      stat:
        path: "/path/vers/tomcat/directory"
      register: tomcat_installed

    - name: Afficher le résultat
      debug:
        msg: "Tomcat est installé"
      when: tomcat_installed.stat.exists

    - name: Afficher le résultat
      debug:
        msg: "Tomcat n'est pas installé"
      when: not tomcat_installed.stat.exists
